clear;
clc;
close all;

plot_files = {
	'q1_theoretical_noise_vs_gamma.png', ...
	'q1_theoretical_sqnr_vs_gamma.png', ...
	'q1_theory_vs_empirical_sqnr.png', ...
	'q2_receiver_A_xcorr_db.png', ...
	'q2_receiver_B_xcorr_db.png', ...
	'q2_psd_before_after_whitening.png', ...
	'q2_receivers_overlay_db.png', ...
	'q2_receivers_window_1_1000_db.png', ...
	'q2_psd_raw_vs_whitened_rad.png', ...
	'q2_receivers_extended_lag_db.png', ...
	'q3_rc_impulse_beta_comparison.png', ...
	'q3_rc_frequency_beta_comparison.png'
};

for k = 1:numel(plot_files)
	if exist(plot_files{k}, 'file') == 2
		delete(plot_files{k});
	end
end

fprintf('\n=== Running solve_q1_quantizer.m ===\n');
run('solve_q1_quantizer.m');

fprintf('\n=== Running solve_q2_radar.m ===\n');
run('solve_q2_radar.m');

fprintf('\n=== Running solve_q3_rc_plots.m ===\n');
run('solve_q3_rc_plots.m');

fprintf('\nAll MATLAB scripts finished.\n');
